learning_log/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('learning_logs.urls', namespace='learning_logs')),
]

learning_logs/urls.py
"""Определяет схемы URL для learning_logs"""

from django.conf.urls import url
from . import views

urlpatterns = [
    # Домашняя страница
    url(r'^$', views.index, name='index'),
    url(r'^topics/$', views.topics, name='topics'),
    url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
    url(r'^new_topic/$', views.new_topic, name="new_topic"),
    url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
]

learning_logs/models.py
from django.db import models


class Topics(models.Model):
    """Тема которую изучает пользователь"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Topics"

    def __str__(self):
        """Возвращает строковое описание модели"""
        return self.text


class Entry(models.Model):
    """Информация изученная пользователем по теме"""
    topic = models.ForeignKey(Topics)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Entries"

    def __str__(self):
        """Возвращает строковое описание модели"""
        if len(self.text) > 50:
            return self.text[:50] + "..."
        else:
            return self.text

learning_logs/forms.py
from django import forms
from .models import Topics, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topics
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render

from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

from .models import Topics
from .forms import TopicForm, EntryForm

# Create your views here.


def index(request):
    """Домашняя страница приложения learning_log"""
    return render(request, 'learning_logs/index.html')


def topics(request):
    """Выводит список тем"""
    topics = Topics.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)


def topic(request, topic_id):
    """Выводит одну тему и все ее записи"""
    topic = Topics.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)


def new_topic(request):
    """Определяет новую тему"""
    if request.method != 'POST':
        # Данные не отправлялись, создаем пустую форму
        form = TopicForm()
    else:
        # Отправлены данные POST, обработаем данные
        form = TopicForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


def new_entry(request, topic_id):
    """Добавляет новую запись по конкретной теме"""
    topic = Topics.objects.get(id=topic_id)
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            # можно передать сразу объект topic, а можно и id : topic.id
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

learning_logs/templates/learning_logs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index of learning log app</title>
</head>
<body>
<p>
    <a href="{% url 'learning_logs:index' %}">Learning Log</a> -
    <a href="{% url 'learning_logs:topics' %}">Ваши темы</a>
</p>
{% block content %}
{% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/index.html
    {% extends 'learning_logs/base.html' %}
    {% block content %}
    <p>Learning Log - поможет вам отслеживать ваше обучение по темам.</p>
    {% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{%  extends 'learning_logs/base.html' %}
{% block content %}
    <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
    <p>Добавить новую запись:</p>
    <form action="{% url 'learning_logs:new_entry' topic.id %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Добавить</button>
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}
{% block content %}
    <p>Добавление новой темы</p>
    <form action="{% url 'learning_logs:new_topic' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Добавить</button>
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}
{% block content %}
    <p>Тема: {{ topic }}</p>
    <p><a href="{% url 'learning_logs:new_entry' topic.id %}">Добавить новую запись</a></p>
    <p>Записи:</p>
    <ul>
        {% for entry in entries %}
            <li>
                <p>{{ entry.date_added|date:'d-m-Y H:i:s' }}</p>
                <p>{{ entry.text|linebreaks }}</p>
            </li>
        {% empty %}
            <li>У вас нет записей</li>
        {% endfor %}
    </ul>
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}

{% block content %}
<p>Темы</p>
<ul>
    {% for topic in topics %}
        <li><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></li>
    {% empty %}
        <li>У вас нет ни одной темы</li>
    {% endfor %}
</ul>
    <a href="{% url 'learning_logs:new_topic' %}">Создать новую тему</a>
{% endblock content %}